### ISSUE TITLE
alikeSoftwares - use singular for "software"

### ISSUE THREAD

**Issue by bzg** [etalab/sill-api#11]

**Comment by garronej** [comment]
Hi @bgz,  
I am divided on this, it is a coding convention to slap an `s` when an identifier is a set of something.  
Writing `software.map(software=> software.id)` while grammatically correct is harder to reason about than `softwares.map(software=> software.id)`.  
I think in this instance coding convention is more important than grammar.  
Coming up with another therm than software could be a solution.
