### ISSUE TITLE
Consider using an array instead of a string for several properties

### ISSUE THREAD

**Issue by bzg** [etalab/sill-api#14]
In `softwareRow`, these are strings: 

```
workshopUrl?
testUrl?
useCasesUrl?
```

For each SILL software, we might have several `workshops`, `testUrl`, `useCasesUrl` (see the plural form for the latter).

`workshopUrl` and `useCaseUrl` (singular is better) are straightforward: they can be arrays of strings.

`testUrl` is different as we might want to add a description along with the Url: e.g. a first "test URL" can be a demo set up by a company, another "test URL" can be the test that the Free Software unit sets up (with your cluster), etc.

WDYT?

**Comment by garronej** [comment]
All valid points
