### ISSUE TITLE
Ajouter softwareComptoirId

### ISSUE THREAD

**Issue by bzg** [etalab/sill-api#18]
Il existe des services qui s'appuient sur des logiciels libres référencés dans le Comptoir du libre sans être référencés dans le SILL.

En listant les services sur code.gouv.fr, l'idée serait de pouvoir visiter la fiche du Comptoir lorsque c'est pertinent.

**Comment by garronej** [comment]
Salut,  

Cette id est déjà présent sous la forme `comptoireDuLibreId`.  

<img width="443" alt="image" src="https://user-images.githubusercontent.com/6702424/167395898-d64a7904-b49f-4e5b-b2eb-822324c60b36.png">

**Comment by garronej** [comment]
La définition du type est [ici](https://github.com/etalab/sill-api/blob/c36aa088e94cb6df61995b73740a85899f14557d/src/model/types.ts#L64-L91)
