### ISSUE TITLE
Add labelUrl (from catalogue.numerique.gouv.fr)

### ISSUE THREAD

**Issue by bzg** [etalab/sill-api#22]
https://code.gouv.fr/data/sill-data.json does not have any information on whether the software is also referenced in https://catalogue.numerique.gouv.fr.

The source information is in https://git.sr.ht/~etalab/sill/tree/master/item/sill.csv, in the `label` column.

Add this information to sill-data.json as `labelUrl`, as a string.

**Comment by garronej** [comment]
see resolution: https://github.com/etalab/sill-web/issues/76#issuecomment-1267202794
